# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPyNG2Lyk0wWE_HqSbpkVwmhFVIWHtvd
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- STEP 1: IMPORTING THE DATA ---
# Using a custom name for our dataframe to keep it clear
raw_data = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')
print(f"Successfully loaded {len(raw_data)} customer records.")

# --- STEP 2: CLEANING UP ---
# TotalCharges has some annoying blank spaces. Let's force them to 0 so we can do math.
raw_data['TotalCharges'] = pd.to_numeric(raw_data['TotalCharges'], errors='coerce').fillna(0)
print("Data cleaning complete: Handled blank values in TotalCharges.")

# --- STEP 3: CREATING PIVOT TABLES FOR GITHUB ---
# I'm grouping these by hand to make sure the counts are accurate for my report
contract_pivot = raw_data.groupby(['Contract', 'Churn']).size().unstack()
contract_pivot.to_csv('Pivot_Contract.csv')

internet_pivot = raw_data.groupby(['InternetService', 'Churn']).size().unstack()
internet_pivot.to_csv('Pivot_Internet.csv')

overall_summary = raw_data['Churn'].value_counts().reset_index()
overall_summary.columns = ['Status', 'Count']
overall_summary.to_csv('Pivot_Overall_Churn.csv', index=False)
print("Pivot tables exported successfully!")

# --- STEP 4: DESIGNING THE DASHBOARD ---
# I'm using a custom color palette: Teal for 'Stayed' and Coral for 'Churned'
my_colors = ['#45b6fe', '#ff6b6b']
sns.set_style("white") # Cleaner, more modern look

fig, axes = plt.subplots(2, 2, figsize=(15, 10))
fig.suptitle('Analysis of Customer Churn Drivers', fontsize=20, color='#333333', weight='bold')

# Plot 1: Big Picture Churn
axes[0, 0].pie(overall_summary['Count'], labels=['Loyal', 'Churned'], autopct='%1.1f%%',
               startangle=140, colors=my_colors, pctdistance=0.85)
axes[0, 0].set_title('Overall Churn Percentage', fontsize=14, weight='bold')

# Plot 2: Contract Risks
contract_pivot.plot(kind='bar', color=my_colors, ax=axes[0, 1], edgecolor='black')
axes[0, 1].set_title('Churn Risk by Contract Type', fontsize=14, weight='bold')
axes[0, 1].set_xticklabels(contract_pivot.index, rotation=0)

# Plot 3: The "Early Exit" Trend (Tenure)
sns.kdeplot(data=raw_data, x='tenure', hue='Churn', palette=my_colors, fill=True, ax=axes[1, 0])
axes[1, 0].set_title('When do customers leave? (Tenure)', fontsize=14, weight='bold')

# Plot 4: Service Quality Check
internet_pivot.plot(kind='bar', color=my_colors, ax=axes[1, 1], edgecolor='black')
axes[1, 1].set_title('Churn by Internet Service Tier', fontsize=14, weight='bold')
axes[1, 1].set_xticklabels(internet_pivot.index, rotation=0)

plt.tight_layout(pad=3.0)
plt.savefig('Churn_Dashboard.png', dpi=300) # Higher quality save
print("Visual dashboard is ready for download!")